import math
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import copy

from ...utils.config import CN
from ...utils.logger import logger
from ...utils.builder import HEAD
from ...utils.misc import param_size
from ...utils.transform import (inverse_sigmoid, batch_cam_extr_transf, batch_cam_intr_projection, bchw_2_bhwc,
                                denormalize, rot6d_to_rotmat, rotmat_to_rot6d)
from ..bricks.transformer import build_transformer
from ..bricks.utils import ManoDecoder
from ..layers.ptEmb_transformer import HORStage2Context, HORStage3Context
from ..layers.petr_transformer import SinePositionalEncoding3D

import imageio
import warnings
import cv2
import time


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def viz_3d(image, joints_2d_proj):

    frame_1 = image.copy()
    for i in range(joints_2d_proj.shape[0]):
        cx = int(joints_2d_proj[i, 0])
        cy = int(joints_2d_proj[i, 1])
        cv2.circle(frame_1, (cx, cy), radius=1, thickness=-1, color=np.array([1.0, 0.0, 0.0]) * 255)

    img_list = [image, frame_1]
    comb_image = np.hstack(img_list)
    imageio.imwrite("tmp/img.png", comb_image)
    time.sleep(5)


class BasePointEmbedHead(nn.Module):

    def __init__(self, cfg: CN):
        super(BasePointEmbedHead, self).__init__()
        self.cfg_transformer = cfg.TRANSFORMER
        self.cfg_position_encoding = cfg.POSITIONAL_ENCODING

        self.with_position = cfg.WITH_POSITION
        self.with_multiview = cfg.WITH_MULTIVIEW
        self.num_query = cfg.NUM_QUERY  #  should equal to the n_vertices + n_joints,
        self.depth_num = cfg.DEPTH_NUM
        self.position_dim = 3 * self.depth_num
        self.position_range = cfg.POSITION_RANGE
        self.LID = cfg.LID
        self.depth_start = cfg.DEPTH_START
        self.depth_end = cfg.DEPTH_END
        self.embed_dims = cfg.EMBED_DIMS
        self.in_channels = cfg.IN_CHANNELS
        self.num_preds = cfg.NUM_PREDS

        # custom args
        self.center_shift = cfg.get("CENTER_SHIFT", False)

        self._build_head_module()
        self.init_weights()
        logger.info(f"{type(self).__name__} has {param_size(self)}M parameters, "
                    f"and got custom args: {self._str_custom_args()}")

    def _str_custom_args(self):
        return (f"center_shift: {self.center_shift}")

    def _build_head_module(self):
        if self.center_shift:
            self.center_shift_layer = nn.Sequential(nn.Linear(self.num_query, self.num_query), nn.ReLU(),
                                                    nn.Linear(self.num_query, 1))

        self.positional_encoding = SinePositionalEncoding3D(num_feats=self.cfg_position_encoding.NUM_FEATS,
                                                            normalize=self.cfg_position_encoding.NORMALIZE)
        self.transformer = build_transformer(self.cfg_transformer)

        # Relative position encoding for hand-object interaction
        self.rel_pos_encoder = nn.Sequential(
            nn.Linear(3, 64),
            nn.ReLU(),
            nn.Linear(64, 1)
        )

        # Project 257-dim features back to 256-dim
        self.feat_proj = nn.Linear(257, 256)

        self.input_proj = nn.Conv2d(self.in_channels, self.embed_dims, kernel_size=1)
        self.adapt_pos3d = nn.Conv2d(self.embed_dims * 3 // 2, self.embed_dims, kernel_size=1, stride=1, padding=0)
        self.position_encoder = nn.Sequential(
            nn.Conv2d(self.position_dim, self.embed_dims * 2, kernel_size=1, stride=1, padding=0),
            nn.ReLU(),
            nn.Conv2d(self.embed_dims * 2, self.embed_dims, kernel_size=1, stride=1, padding=0),
        )
        if getattr(self, "build_query_modules", True):
            self.reg_branches = nn.ModuleList()
            for i in range(self.num_preds):
                reg_branch = nn.Sequential(nn.Linear(self.pt_feat_dim, self.pt_feat_dim), nn.ReLU(),
                                           nn.Linear(self.pt_feat_dim, 3))
                self.reg_branches.append(reg_branch)

            self.reference_embed = nn.Embedding(self.num_query, self.embed_dims)
            self.query_embedding = nn.Sequential(
                nn.Linear(6 + (self.embed_dims * 3 // 2), self.embed_dims),
                nn.ReLU(),
                nn.Linear(self.embed_dims, self.pt_feat_dim),
            )

    def position_embeding(self, img_feat, img_metas, masks=None):
        eps = 1e-5
        inp_img_h, inp_img_w = img_metas['inp_img_shape']
        B, N, C, H, W = img_feat.shape
        coords_h = torch.arange(H, device=img_feat.device).float() * inp_img_h / H  # U
        coords_w = torch.arange(W, device=img_feat.device).float() * inp_img_w / W  # V

        if self.LID:
            index = torch.arange(start=0, end=self.depth_num, step=1, device=img_feat.device).float()
            index_plus1 = index + 1
            bin_size = (self.depth_end - self.depth_start) / (self.depth_num * (1 + self.depth_num))
            coords_d = self.depth_start + bin_size * index * index_plus1
        else:
            index = torch.arange(start=0, end=self.depth_num, step=1, device=img_feat.device).float()
            bin_size = (self.depth_end - self.depth_start) / self.depth_num
            coords_d = self.depth_start + bin_size * index

        D = coords_d.shape[0]

        # (W, H, D, 3)
        coords = torch.stack(torch.meshgrid([coords_w, coords_h, coords_d], indexing='ij')).permute(1, 2, 3, 0)

        # ===== 1. using camera intrinsic to convert UVD 2 XYZ  >>>>>>
        INTR = img_metas["cam_intr"]  # (B, N, 3, 3)
        fx = INTR[..., 0, 0].unsqueeze(dim=-1)  # (B, N, 1)
        fy = INTR[..., 1, 1].unsqueeze(dim=-1)  # (B, N, 1)
        cx = INTR[..., 0, 2].unsqueeze(dim=-1)  # (B, N, 1)
        cy = INTR[..., 1, 2].unsqueeze(dim=-1)  # (B, N, 1)
        cam_param = torch.cat((fx, fy, cx, cy), dim=-1)  # (B, N, 4)
        cam_param = cam_param.view(B, N, 1, 1, 1, 4).repeat(1, 1, W, H, D, 1)  # (B, N, W, H, D, 4)

        coords_uv, coords_d = coords[..., :2], coords[..., 2:3]  # (W, H, D, 2), (W, H, D, 1)
        coords_uv = coords_uv.view(1, 1, W, H, D, 2).repeat(B, N, 1, 1, 1, 1)  # (B, N, W, H, D, 2)
        coords_d = coords_d.view(1, 1, W, H, D, 1).repeat(B, N, 1, 1, 1, 1)  # (B, N, W, H, D, 1)

        coords_uv = (coords_uv - cam_param[..., 2:4]) / cam_param[..., :2]  # (B, N, W, H, D, 2)
        coords_xy = coords_uv * coords_d
        coords_z = coords_d
        coords = torch.cat((coords_xy, coords_z), dim=-1)  # (B, N, W, H, D, 3)

        # ===== 2. using camera extrinsic to transfer childs' XYZ 2 parent's space >>>>>>
        EXTR = img_metas["cam_extr"]  # (B, N, 4, 4)
        coords = torch.cat((coords, torch.ones_like(coords[..., :1])), -1)
        coords = coords.unsqueeze(-1)  # (B, N, W, H, D, 4, 1)
        EXTR = EXTR.view(B, N, 1, 1, 1, 4, 4).repeat(1, 1, W, H, D, 1, 1)  # (B, N, W, H, D, 4, 4)
        coords3d = torch.matmul(EXTR, coords).squeeze(-1)[..., :3]  # (B, N, W, H, D, 3),  xyz in parent's space

        coords3d_absolute = copy.deepcopy(coords3d)
        # ===== 3. using position range to normalize coords3d
        #                 0     1     2     3     4     5
        # position_range [xmin, ymin, zmin, xmax, ymax, zmax]
        coords3d[..., 0:1] = (coords3d[..., 0:1] - self.position_range[0]) / \
                                (self.position_range[3] - self.position_range[0])
        coords3d[..., 1:2] = (coords3d[..., 1:2] - self.position_range[1]) / \
                                (self.position_range[4] - self.position_range[1])
        coords3d[..., 2:3] = (coords3d[..., 2:3] - self.position_range[2]) / \
                                (self.position_range[5] - self.position_range[2])

        coords_mask = (coords3d > 1.0) | (coords3d < 0.0)  # (B, N, W, H, D, 3)

        #coords_mask = coords_mask.flatten(-2).sum(-1) > (D * 0.5)  # (B, N, W, H)
        #coords_mask = masks | coords_mask.permute(0, 1, 3, 2)  # (B, N, H, W)
        coords3d_feat = coords3d.permute(0, 1, 4, 5, 3, 2).contiguous().view(B * N, -1, H, W)  # (B*N, 3*D, H, W)
        coords3d_feat = inverse_sigmoid(coords3d_feat)
        coords_position_embeding = self.position_encoder(coords3d_feat)  # res: (B*N, 256, H, W), 256 is self.embed_dims

        return coords_position_embeding.view(B, N, self.embed_dims, H, W), coords3d, coords3d_absolute, coords_mask

    def init_weights(self):
        # The initialization for transformer is important, we leave it to the child class to decide.
        ### self.transformer.init_weights()
        if hasattr(self, "reference_embed"):
            nn.init.uniform_(self.reference_embed.weight.data, 0, 1)

    def forward(self, mlvl_feat, img_metas, reference_points, template_mesh, **kwargs):
        raise NotImplementedError(f"forward not implemented in base BasePointEmbedHead")


@HEAD.register_module()  # proj_selfagg
class HOR_Projective_SelfAggregation_Head(BasePointEmbedHead):

    def __init__(self, cfg: CN):
        self.data_preset_cfg = cfg.DATA_PRESET
        self.radius = cfg.get('RADIUS_SAMPLE', 0.1)
        self.nsample = cfg.get("N_SAMPLE", 2048)
        self.view_nums = cfg.get("VIEW_NUMS", 8)
        self.pt_feat_dim = cfg.POINTS_FEAT_DIM
        self.merge_mode = cfg.get("CAM_FEAT_MERGE", "attn")
        self.build_query_modules = False
        self.transformer_center_idx = cfg.TRANSFORMER.get(
            "TRANSFORMER_CENTER_IDX",
            self.data_preset_cfg.CENTER_IDX,
        )
        self.stage3_hand_update_min_scale = float(cfg.get("STAGE3_HAND_UPDATE_MIN_SCALE", 0.2))
        self.stage3_obj_feat_min_scale = float(cfg.get("STAGE3_OBJ_FEAT_MIN_SCALE", 0.2))
        self.stage3_pose_delta_min_scale = float(cfg.get("STAGE3_POSE_DELTA_MIN_SCALE", 0.1))
        self.stage3_init_rot_min_scale = float(cfg.get("STAGE3_INIT_ROT_MIN_SCALE", 0.1))
        super(HOR_Projective_SelfAggregation_Head, self).__init__(cfg)

    def _build_head_module(self):
        super(HOR_Projective_SelfAggregation_Head, self)._build_head_module()

        self.merge_net_feature = nn.ModuleList()
        self.merge_net_feature.append(
            nn.Sequential(nn.Linear(self.embed_dims, self.embed_dims), nn.ReLU(),
                          nn.Linear(self.embed_dims, self.embed_dims // 2)))
        self.merge_net_feature.append(
            nn.Sequential(nn.Linear(self.embed_dims // 2, self.embed_dims // 2), nn.ReLU(),
                          nn.Linear(self.embed_dims // 2, self.embed_dims)))
        self.obj_init_rot_regressor = nn.Sequential(
            nn.Linear(self.embed_dims * 2, self.embed_dims),
            nn.ReLU(),
            nn.Linear(self.embed_dims, self.embed_dims // 2),
            nn.ReLU(),
            nn.Linear(self.embed_dims // 2, 6),
        )
        self.obj_pose_delta_regressor = nn.Sequential(
            nn.Linear(self.pt_feat_dim + self.embed_dims * 2 + 9, self.pt_feat_dim),
            nn.ReLU(),
            nn.Linear(self.pt_feat_dim, self.pt_feat_dim // 2),
            nn.ReLU(),
            nn.Linear(self.pt_feat_dim // 2, 9),
        )
        self.obj_feat_fuser = nn.Sequential(
            nn.Linear(self.pt_feat_dim * 2, self.pt_feat_dim),
            nn.ReLU(),
            nn.Linear(self.pt_feat_dim, self.pt_feat_dim),
        )
        self.hand_anchor_feat_adapter = nn.Sequential(
            nn.Linear(self.pt_feat_dim, self.pt_feat_dim),
            nn.ReLU(),
            nn.Linear(self.pt_feat_dim, self.pt_feat_dim),
        )
        self.hand_joint_feat_adapter = nn.Sequential(
            nn.Linear(self.pt_feat_dim, self.pt_feat_dim),
            nn.ReLU(),
            nn.Linear(self.pt_feat_dim, self.pt_feat_dim),
        )
        self.final_joint_mano_regressor = nn.Sequential(
            nn.Linear(self.pt_feat_dim + 3, self.pt_feat_dim),
            nn.ReLU(),
            nn.Linear(self.pt_feat_dim, self.pt_feat_dim // 2),
            nn.ReLU(),
            nn.Linear(self.pt_feat_dim // 2, 109),
        )
        self.final_mesh_mano_regressor = nn.Sequential(
            nn.Linear(self.pt_feat_dim + 3, self.pt_feat_dim),
            nn.ReLU(),
            nn.Linear(self.pt_feat_dim, self.pt_feat_dim // 2),
            nn.ReLU(),
            nn.Linear(self.pt_feat_dim // 2, 109),
        )
        self.register_buffer("identity_rot6d", torch.tensor([1.0, 0.0, 0.0, 0.0, 1.0, 0.0], dtype=torch.float32))
        self.mano_scale = float(self.data_preset_cfg.BBOX_3D_SIZE) / 2.0
        self.mano_decoder = ManoDecoder(
            self.transformer_center_idx,
            self.data_preset_cfg.BBOX_3D_SIZE,
            tuple(self.data_preset_cfg.IMAGE_SIZE),
        )
        logger.warning(f"{type(self).__name__} build done")

    def _str_custom_args(self):
        str_ = super()._str_custom_args()
        return str_ + ", " + f"agg_merge_mode: {self.merge_mode}"

    def merge_features_mv(self, q, merge_net, master_id):
        """
            q: [B, nsample, N, 256]
            q_merged: [B, nsample, 256]
        """
        master_is_zero = torch.sum(master_id)
        assert master_is_zero == 0, "only support master_id is 0"
        cam_num = q.shape[2]

        q1 = q[:, :, 0, :]
        q = merge_net[0](q)
        master_features = q[:, :, 0, :]  # [B, nsample, 128]
        other_features = q[:, :, 1:, :]  # [B, nsample, 7, 128]
        q = torch.matmul(other_features, master_features.unsqueeze(-1))  # [B, nsample, 7, 1]
        q = torch.matmul(other_features.transpose(2, 3), q).squeeze(-1)
        q_merged = merge_net[1](q) / cam_num  # [B, nsample, 256]
        q_merged = q1 + q_merged
        return q_merged

    def _debug_viz(self, debug_metas, src_points_sub, idx=0):
        # Visualize the first view
        img_single = debug_metas["img"][idx]
        image = img_single.detach().cpu().unsqueeze(0)
        image = bchw_2_bhwc(denormalize(image, [0.5, 0.5, 0.5], [1, 1, 1], inplace=False))
        img_h, img_w = self.data_preset_cfg.IMAGE_SIZE
        image = image.mul_(255.0).view(1, img_h, img_w, 3).squeeze(0).numpy().astype(np.uint8)  # (B, H, W, 3)
        vis_points = src_points_sub[idx]
        viz_3d(image, vis_points)

    def build_object_queries(self, obj_template, hand_center_point, obj_center_point):
        if obj_template.dim() == 2:
            obj_template = obj_template.unsqueeze(0).expand(hand_center_point.shape[0], -1, -1)
        obj_trans_master = obj_center_point - hand_center_point
        obj_template_norm = obj_template / self.mano_scale
        obj_trans_norm = obj_trans_master / self.mano_scale
        obj_xyz_norm = obj_template_norm + obj_trans_norm
        obj_xyz_master = (obj_xyz_norm * self.mano_scale) + hand_center_point
        return obj_xyz_norm, obj_xyz_master, obj_trans_master, obj_trans_norm

    def predict_mano_from_tokens(self, token_feats, token_xyz, regressor):
        pooled_feat = torch.cat((token_feats, token_xyz), dim=-1).mean(dim=1)
        mano_params = regressor(pooled_feat)
        pred_hand_pose = mano_params[:, :96]
        pred_shape = mano_params[:, 96:106]
        pred_cam = mano_params[:, 106:]
        pred_cam = torch.cat((F.relu(pred_cam[:, 0:1]), pred_cam[:, 1:]), dim=1)
        coord_xyz, _, pose_euler, shape, cam = self.mano_decoder(pred_hand_pose, pred_shape, pred_cam)
        coord_xyz = coord_xyz * self.mano_scale
        pred_mano_params = {
            "pose_euler": pose_euler,
            "shape": shape,
            "cam": cam,
        }
        return coord_xyz, pred_mano_params

    def sample_hand_mesh_features_from_master(self, feat_map, hand_mesh_xyz_master, img_metas, inp_res, batch_size, num_cams):
        hand_mesh_2d = self.project_points_to_views(hand_mesh_xyz_master, img_metas, inp_res)
        return self.sample_multiview_features(
            feat_map,
            hand_mesh_2d,
            batch_size,
            num_cams,
            hand_mesh_xyz_master.shape[1],
        )

    def build_object_points_from_pose(self, obj_template, hand_center_point, rot6d, trans_norm):
        if obj_template.dim() == 2:
            obj_template = obj_template.unsqueeze(0).expand(rot6d.shape[0], -1, -1)
        obj_template_norm = obj_template / self.mano_scale
        rotmat = rot6d_to_rotmat(rot6d.reshape(-1, 6)).view(*rot6d.shape[:-1], 3, 3)
        if (
            obj_template_norm.dim() == rot6d.dim() + 1
            and obj_template_norm.shape[:-2] == rot6d.shape[:-1]
        ):
            obj_template_expand = obj_template_norm
        else:
            expand_shape = [1] * (rot6d.dim() - 1) + [obj_template_norm.shape[-2], 3]
            obj_template_expand = obj_template_norm.view(*expand_shape).expand(*rot6d.shape[:-1], obj_template_norm.shape[-2], 3)
        obj_xyz_norm = torch.matmul(obj_template_expand, rotmat.transpose(-1, -2)) + trans_norm.unsqueeze(-2)
        if hand_center_point.dim() == rot6d.dim():
            hand_center_expand = hand_center_point
        else:
            hand_center_expand = hand_center_point.view(*([1] * (rot6d.dim() - 2)), *hand_center_point.shape)
        obj_xyz_master = (obj_xyz_norm * self.mano_scale) + hand_center_expand
        obj_center_master = obj_xyz_master.mean(dim=-2, keepdim=True)
        obj_trans = trans_norm * self.mano_scale
        return obj_xyz_norm, obj_xyz_master, obj_center_master, obj_trans

    def predict_initial_object_rotation(self, feat_map, obj_center_feat, warmup_scale=1.0):
        global_mv_feat = feat_map.mean(dim=(1, 3, 4))
        init_feat = torch.cat((global_mv_feat, obj_center_feat), dim=-1)
        identity_rot = self.identity_rot6d.unsqueeze(0).expand(global_mv_feat.shape[0], -1)
        raw_rot_delta = self.obj_init_rot_regressor(init_feat)
        init_rot_seed = identity_rot + (warmup_scale * raw_rot_delta)
        init_rotmat = rot6d_to_rotmat(init_rot_seed)
        init_rot6d = rotmat_to_rot6d(init_rotmat)
        return init_rot6d, global_mv_feat

    def update_object_pose(self, obj_feats, obj_center_feat, global_mv_feat, current_rot6d, current_trans_norm, warmup_scale=1.0):
        global_obj_feat = obj_feats.mean(dim=1)
        pose_input = torch.cat((global_obj_feat, obj_center_feat, global_mv_feat, current_rot6d, current_trans_norm), dim=-1)
        delta_pose = self.obj_pose_delta_regressor(pose_input) * warmup_scale
        next_rot_seed = current_rot6d + delta_pose[:, :6]
        next_rotmat = rot6d_to_rotmat(next_rot_seed)
        next_rot6d = rotmat_to_rot6d(next_rotmat)
        next_trans_norm = current_trans_norm + delta_pose[:, 6:]
        return next_rot6d, next_trans_norm

    def build_stage3_context(
        self,
        obj_template,
        hand_center_point,
        current_rot6d,
        current_trans_norm,
        feat_map,
        img_metas,
        inp_res,
        obj_center_feat,
        global_mv_feat,
        hand_update_scale,
        obj_feat_update_scale,
        pose_delta_scale,
    ):
        return HORStage3Context(
            obj_template=obj_template,
            hand_center_point=hand_center_point,
            current_rot6d=current_rot6d,
            current_trans_norm=current_trans_norm,
            feat_map=feat_map,
            img_metas=img_metas,
            inp_res=inp_res,
            obj_center_feat=obj_center_feat,
            global_mv_feat=global_mv_feat,
            sample_multiview_features_fn=self.sample_multiview_features,
            project_points_to_views_fn=self.project_points_to_views,
            build_object_points_from_pose_fn=self.build_object_points_from_pose,
            update_object_pose_fn=self.update_object_pose,
            obj_feat_fuser=self.obj_feat_fuser,
            hand_update_scale=hand_update_scale,
            obj_feat_update_scale=obj_feat_update_scale,
            pose_delta_scale=pose_delta_scale,
        )

    def build_stage2_context(self, hand_center_point, anchor_verts_xyz_master, anchor_verts_xyz_norm, anchor_verts_feats_norm):
        return HORStage2Context(
            hand_center_point=hand_center_point,
            anchor_verts_xyz_master=anchor_verts_xyz_master,
            anchor_verts_xyz_norm=anchor_verts_xyz_norm,
            anchor_verts_feats_norm=anchor_verts_feats_norm,
        )

    def project_points_to_views(self, points_master, img_metas, inp_res):
        batch_size, num_cams = img_metas["cam_intr"].shape[:2]
        points_multiview = points_master.unsqueeze(1).repeat(1, num_cams, 1, 1)
        points_cam = batch_cam_extr_transf(torch.linalg.inv(img_metas["cam_extr"]), points_multiview)
        points_2d = batch_cam_intr_projection(img_metas["cam_intr"], points_cam)
        points_2d = points_2d.flatten(0, 1).unsqueeze(-2)
        points_2d = torch.einsum("bijk,k->bijk", points_2d, 1.0 / inp_res)
        return points_2d * 2 - 1

    def sample_multiview_features(self, feat_map, query_2d, batch_size, num_cams, num_points):
        feat_dim = feat_map.size(2)
        sampled_feats = F.grid_sample(feat_map.flatten(0, 1), query_2d, align_corners=False)
        sampled_feats = sampled_feats.squeeze(-1).reshape(batch_size, num_cams, feat_dim, num_points).permute(0, 3, 1, 2)
        if self.merge_mode == "attn":
            return self.merge_features_mv(sampled_feats, self.merge_net_feature, torch.zeros(batch_size, dtype=torch.long, device=feat_map.device))
        if self.merge_mode == "sum":
            return torch.sum(sampled_feats, dim=-2)
        raise ValueError(f"CAM_FEAT_MERGE must in [attn, sum], default sum, got {self.merge_mode}")

    def fuse_hand_joint_features(self, hand_xyz, hand_feats, joint_xyz, joint_feats):
        hand_xyz_exp = hand_xyz.unsqueeze(2)
        joint_xyz_exp = joint_xyz.unsqueeze(1)

        diff = hand_xyz_exp - joint_xyz_exp
        hand_joint_dist = torch.sqrt(torch.sum(diff ** 2, dim=-1) + 1e-6)

        hand_dist_feat = torch.mean(hand_joint_dist, dim=-1, keepdim=True)
        joint_dist_feat = torch.mean(hand_joint_dist, dim=1, keepdim=False).unsqueeze(-1)

        hand_joint_rel = joint_xyz_exp - hand_xyz_exp
        hand_joint_rel_feat = self.rel_pos_encoder(hand_joint_rel)
        hand_rel_feat = torch.mean(hand_joint_rel_feat, dim=2)
        joint_rel_feat = torch.mean(hand_joint_rel_feat, dim=1)

        hand_feats = self.feat_proj(torch.cat([hand_feats, hand_dist_feat], dim=-1) + hand_rel_feat)
        joint_feats = self.feat_proj(torch.cat([joint_feats, joint_dist_feat], dim=-1) + joint_rel_feat)
        return hand_feats, joint_feats

    def forward(self, mlvl_feat, mano_3d_sv, img_metas, reference_hand, reference_obj, obj_template, **kwargs):
        results = dict()
        interaction_mode = kwargs.get("interaction_mode", "ho")
        stage3_warmup = float(kwargs.get("stage3_warmup", 1.0))
        x = mlvl_feat
        batch_size, num_cams = x.size(0), x.size(1)
        mano_3d_sv = mano_3d_sv.view(batch_size, num_cams, *mano_3d_sv.shape[1:])  # (B, N, 799, 3)
        batch_idx = torch.arange(batch_size, device=mano_3d_sv.device)
        mano_3d_master = mano_3d_sv[batch_idx, img_metas["master_id"]]  # (B, 799, 3)

        inp_img_h, inp_img_w = img_metas["inp_img_shape"]
        inp_res = torch.tensor([inp_img_w, inp_img_h], device=x.device, dtype=torch.float32)
        img_metas["inp_res"] = inp_res
        masks = x.new_zeros((batch_size, num_cams, inp_img_h, inp_img_w))
        x = self.input_proj(x.flatten(0, 1))
        x = x.view(batch_size, num_cams, *x.shape[-3:])  # [B, N, 256, H, W]
        feat_dim = x.size(2)
        assert feat_dim == self.pt_feat_dim, "self.pt_feat_dim should be equal to feat_dim"
        masks = F.interpolate(masks, size=x.shape[-2:]).to(torch.bool)

        sin_embed = self.positional_encoding(masks)
        sin_embed = self.adapt_pos3d(sin_embed.flatten(0, 1)).view(x.size())  # (B, N, 256, H, W)
        x = x + sin_embed

        hand_center_point = reference_hand[:, self.transformer_center_idx:self.transformer_center_idx+1, :]
        obj_center_point = reference_obj
        _, obj_xyz_master_init, obj_trans_master, obj_trans_norm = self.build_object_queries(
            obj_template=obj_template,
            hand_center_point=hand_center_point,
            obj_center_point=obj_center_point,
        )

        ref_hand_mesh = mano_3d_master + hand_center_point
        ref_hand_mesh_2d = self.project_points_to_views(ref_hand_mesh, img_metas, inp_res)
        ref_hand_joints_2d = self.project_points_to_views(reference_hand, img_metas, inp_res)
        obj_center_2d = self.project_points_to_views(obj_center_point, img_metas, inp_res)

        hand_mesh_feats = self.sample_multiview_features(x, ref_hand_mesh_2d, batch_size, num_cams, ref_hand_mesh.shape[1])
        hand_mesh_xyz_norm = (ref_hand_mesh - hand_center_point) / self.mano_scale
        hand_joints_xyz_norm = (reference_hand - hand_center_point) / self.mano_scale

        if interaction_mode == "hand":
            anchor_verts_xyz_norm = hand_mesh_xyz_norm[:, :778]
            anchor_verts_xyz_master = ref_hand_mesh[:, :778]
            anchor_verts_feats_norm = hand_mesh_feats[:, :778]
            hand_joint_feats = self.sample_multiview_features(x, ref_hand_joints_2d, batch_size, num_cams, reference_hand.shape[1])
            anchor_feats, hand_joint_feats = self.fuse_hand_joint_features(
                hand_xyz=anchor_verts_xyz_norm,
                hand_feats=anchor_verts_feats_norm,
                joint_xyz=hand_joints_xyz_norm,
                joint_feats=hand_joint_feats,
            )
            anchor_feats = self.hand_anchor_feat_adapter(anchor_feats)
            hand_joint_feats = self.hand_joint_feat_adapter(hand_joint_feats)

            stage2_context = self.build_stage2_context(
                hand_center_point,
                anchor_verts_xyz_master,
                anchor_verts_xyz_norm,
                anchor_feats,
            )
            transformer_outputs = self.transformer(
                query_xyz=hand_joints_xyz_norm,
                query_feat=hand_joint_feats,
                pt_xyz=anchor_verts_xyz_norm,
                pt_feats=anchor_feats,
                interaction_mode="hand",
                stage2_context=stage2_context,
            )
            all_hand_xyz = transformer_outputs.all_hand_mesh_xyz_master
            results["all_hand_joints_xyz_master"] = transformer_outputs.all_hand_joints_xyz_master
            kp_joint_feats_norm = transformer_outputs.final_hand_mesh_feats_norm[:, 778:]
            kp_joint_xyz_norm = transformer_outputs.final_hand_mesh_xyz_norm[:, 778:]
            pred_kp_mano_mesh_xyz_rel, pred_kp_mano_params_master = self.predict_mano_from_tokens(
                kp_joint_feats_norm,
                kp_joint_xyz_norm,
                self.final_joint_mano_regressor,
            )
            pred_kp_mano_mesh_xyz_master = pred_kp_mano_mesh_xyz_rel + hand_center_point

            n_layers = all_hand_xyz.shape[0]
            all_obj_xyz = obj_xyz_master_init.unsqueeze(0).expand(n_layers, -1, -1, -1)
            all_obj_center = obj_center_point.unsqueeze(0).expand(n_layers, -1, -1, -1)
            all_obj_rot6d = self.identity_rot6d.view(1, 1, 6).expand(n_layers, batch_size, -1)
            all_obj_trans = obj_trans_master.squeeze(1).unsqueeze(0).expand(n_layers, -1, -1)
            results["pred_obj_trans_master"] = obj_trans_master
            pred_mano_mesh_xyz_master = pred_kp_mano_mesh_xyz_master
            pred_mano_params_master = pred_kp_mano_params_master
            results["pred_kp_mano_mesh_xyz_master"] = pred_kp_mano_mesh_xyz_master
            results["pred_kp_mano_params_master"] = pred_kp_mano_params_master
        else:
            hand_update_scale = self.stage3_hand_update_min_scale + (1.0 - self.stage3_hand_update_min_scale) * stage3_warmup
            obj_feat_update_scale = self.stage3_obj_feat_min_scale + (1.0 - self.stage3_obj_feat_min_scale) * stage3_warmup
            pose_delta_scale = self.stage3_pose_delta_min_scale + (1.0 - self.stage3_pose_delta_min_scale) * stage3_warmup
            init_rot_scale = self.stage3_init_rot_min_scale + (1.0 - self.stage3_init_rot_min_scale) * stage3_warmup
            obj_center_feat = self.sample_multiview_features(x, obj_center_2d, batch_size, num_cams, 1).squeeze(1)

            anchor_verts_xyz_norm = hand_mesh_xyz_norm[:, :778]
            anchor_verts_xyz_master = ref_hand_mesh[:, :778]
            anchor_verts_feats_norm = hand_mesh_feats[:, :778]
            hand_joint_feats = self.sample_multiview_features(x, ref_hand_joints_2d, batch_size, num_cams, reference_hand.shape[1])
            anchor_feats, hand_joint_feats = self.fuse_hand_joint_features(
                hand_xyz=anchor_verts_xyz_norm,
                hand_feats=anchor_verts_feats_norm,
                joint_xyz=hand_joints_xyz_norm,
                joint_feats=hand_joint_feats,
            )
            anchor_feats = self.hand_anchor_feat_adapter(anchor_feats)
            hand_joint_feats = self.hand_joint_feat_adapter(hand_joint_feats)
            stage2_context = self.build_stage2_context(
                hand_center_point,
                anchor_verts_xyz_master,
                anchor_verts_xyz_norm,
                anchor_feats,
            )
            kp_transformer_outputs = self.transformer(
                query_xyz=hand_joints_xyz_norm,
                query_feat=hand_joint_feats,
                pt_xyz=anchor_verts_xyz_norm,
                pt_feats=anchor_feats,
                interaction_mode="hand",
                stage2_context=stage2_context,
            )
            results["all_hand_joints_xyz_master"] = kp_transformer_outputs.all_hand_joints_xyz_master
            kp_joint_feats_norm = kp_transformer_outputs.final_hand_mesh_feats_norm[:, 778:]
            kp_joint_xyz_norm = kp_transformer_outputs.final_hand_mesh_xyz_norm[:, 778:]
            pred_kp_mano_mesh_xyz_rel, pred_kp_mano_params_master = self.predict_mano_from_tokens(
                kp_joint_feats_norm,
                kp_joint_xyz_norm,
                self.final_joint_mano_regressor,
            )
            pred_kp_mano_mesh_xyz_master = pred_kp_mano_mesh_xyz_rel + hand_center_point
            pred_kp_mano_mesh_xyz_norm = pred_kp_mano_mesh_xyz_rel / self.mano_scale
            current_hand_mesh_xyz_norm = pred_kp_mano_mesh_xyz_norm
            current_hand_mesh_feats_norm = self.sample_hand_mesh_features_from_master(
                x,
                pred_kp_mano_mesh_xyz_master,
                img_metas,
                inp_res,
                batch_size,
                num_cams,
            )
            current_rot6d, global_mv_feat = self.predict_initial_object_rotation(x, obj_center_feat, warmup_scale=init_rot_scale)
            current_trans_norm = obj_trans_norm.squeeze(1)
            stage3_context = self.build_stage3_context(
                obj_template=obj_template,
                hand_center_point=hand_center_point,
                current_rot6d=current_rot6d,
                current_trans_norm=current_trans_norm,
                feat_map=x,
                img_metas=img_metas,
                inp_res=inp_res,
                obj_center_feat=obj_center_feat,
                global_mv_feat=global_mv_feat,
                hand_update_scale=hand_update_scale,
                obj_feat_update_scale=obj_feat_update_scale,
                pose_delta_scale=pose_delta_scale,
            )
            transformer_outputs = self.transformer(
                query_xyz=current_hand_mesh_xyz_norm,
                query_feat=current_hand_mesh_feats_norm,
                pt_xyz=None,
                pt_feats=None,
                interaction_mode="mesh_obj",
                stage3_context=stage3_context,
            )

            all_hand_xyz = transformer_outputs.all_hand_mesh_xyz_master
            all_obj_xyz = transformer_outputs.all_obj_xyz_master
            all_obj_center = transformer_outputs.all_obj_center_xyz_master
            all_obj_rot6d = transformer_outputs.all_obj_rot6d
            all_obj_trans = transformer_outputs.all_obj_trans

            pred_mesh_mano_mesh_xyz_rel, pred_mesh_mano_params_master = self.predict_mano_from_tokens(
                transformer_outputs.final_hand_mesh_feats_norm,
                transformer_outputs.final_hand_mesh_xyz_norm,
                self.final_mesh_mano_regressor,
            )
            pred_mesh_mano_mesh_xyz_master = pred_mesh_mano_mesh_xyz_rel + hand_center_point
            pred_mano_mesh_xyz_master = pred_mesh_mano_mesh_xyz_master
            pred_mano_params_master = pred_mesh_mano_params_master
            results["pred_kp_mano_mesh_xyz_master"] = pred_kp_mano_mesh_xyz_master
            results["pred_kp_mano_params_master"] = pred_kp_mano_params_master
            results["pred_mesh_mano_mesh_xyz_master"] = pred_mesh_mano_mesh_xyz_master
            results["pred_mesh_mano_params_master"] = pred_mesh_mano_params_master
            results["pred_obj_trans_master"] = all_obj_trans[-1].unsqueeze(1)

        results["all_hand_mesh_xyz_master"] = all_hand_xyz
        results["all_obj_xyz_master"] = all_obj_xyz
        results["all_obj_center_xyz_master"] = all_obj_center
        results["all_obj_rot6d"] = all_obj_rot6d
        results["all_obj_trans"] = all_obj_trans
        results["pred_mano_mesh_xyz_master"] = pred_mano_mesh_xyz_master
        results["pred_mano_params_master"] = pred_mano_params_master
        if "pred_obj_trans_master" not in results:
            results["pred_obj_trans_master"] = obj_trans_master
        results["interaction_mode"] = interaction_mode
        # results["obj_xyz"] = obj_xyz_ori
        # results["enhanced_img_feat"] = x

        return results
