TRAIN:
  MANUAL_SEED: 1
  CONV_REPEATABLE: true
  BATCH_SIZE: 8
  EPOCH: 3
  OPTIMIZER: adam
  LR: 0.0001
  WEIGHT_DECAY: 0.0
  SCHEDULER: StepLR
  LR_DECAY_STEP:
  - 70
  LR_DECAY_GAMMA: 0.1
  LOG_INTERVAL: 1
  FIND_UNUSED_PARAMETERS: false
  DEBUG_LOGS: false
  STATIC_GRAPH: false
  STAGE1_END_EPOCH: 2
  STAGE2_WARMUP_EPOCHS: 6
  GRAD_CLIP_ENABLED: true
  GRAD_CLIP:
    TYPE: 2
    NORM: 1.0
DATASET:
  TRAIN:
    TYPE: DexYCBMultiView
    DATA_MODE: 3D
    DATA_ROOT: /media/hl/nvme1TB/datasets
    DATA_SPLIT: train
    SETUP: s0
    N_VIEWS: 8
    USE_LEFT_HAND: false
    FILTER_INVISIBLE_HAND: true
    MASTER_SYSTEM: as_constant_camera
    TRANSFORM:
      TYPE: SimpleTransform3DMultiView
      AUG: true
      CENTER_JIT: 0.0
      SCALE_JIT: 0.02
      COLOR_JIT: 0.3
      ROT_JIT: 5
      ROT_PROB: 0.2
      OCCLUSION: false
      OCCLUSION_PROB: 0.0
      MIN_JOINTS_IN_RAW: 3
      MIN_JOINTS_AFTER_CROP: 3
    SKIP_FRAMES: 400
    USE_CACHE: false
  TEST:
    TYPE: DexYCBMultiView
    DATA_MODE: 3D
    DATA_ROOT: /media/hl/nvme1TB/datasets
    DATA_SPLIT: test
    SETUP: s0
    N_VIEWS: 8
    USE_LEFT_HAND: false
    FILTER_INVISIBLE_HAND: true
    TEST_WITH_MULTIVIEW: true
    MASTER_SYSTEM: as_constant_camera
    TRANSFORM:
      TYPE: SimpleTransform3DMultiView
      AUG: false
    SKIP_FRAMES: 400
    USE_CACHE: false
DATA_PRESET:
  MODE: mv
  USE_CACHE: true
  IMAGE_SIZE:
  - 256
  - 256
  CENTER_IDX: 9
  BBOX_3D_SIZE: 0.4
  NUM_JOINTS: 21
  NUM_VERTS: 778
  WITH_HEATMAP: true
  HEATMAP_SIZE:
  - 32
  - 32
  HEATMAP_SIGMA: 2.0
  WITH_OBJ_OCC: true
  OBJ_OCC_SIZE:
  - 32
  - 32
  OBJ_OCC_RADIUS: 1
  OBJ_OCC_BLUR_SIGMA: 1.0
  WITH_MASK: false
  BBOX_EXPAND_RATIO: 2.0
  STAGE12_BBOX_EXPAND_RATIO: 1.5
  STAGE2_HAND_OBJ_SCALE: 1.25
MODEL:
  TYPE: POEM_Heatmap
  PRETRAINED: null
  BACKBONE:
    TYPE: ResNet34
    PRETRAINED: true
    FREEZE_BATCHNORM: true
  HEAD:
    TYPE: HOR_Projective_SelfAggregation_Head
    TRANSFORMER:
      TYPE: HORTR
      N_BLOCKS: 3
      INPUT_FEAT_DIM: 256
      NUM_HIDDEN_LAYERS: 4
      NUM_ATTENTION_HEADS: 4
      DROPOUT: 0.1
      N_NEIGHBOR: 32
      N_NEIGHBOR_QUERY: 32
      POINTS_FEAT_DIM: 256
      WITH_POSI_EMBED: true
      PREDICT_INV_SIGMOID: true
      PARAMETRIC_OUTPUT: true
      TRANSFORMER_CENTER_IDX: 9
    POSITIONAL_ENCODING:
      TYPE: SinePositionalEncoding3D
      NUM_FEATS: 128
      NORMALIZE: true
    WITH_POSITION: true
    WITH_MULTIVIEW: true
    NUM_QUERY: 799
    NUM_PREDS: 3
    DEPTH_NUM: 32
    POSITION_RANGE:
    - -1.2
    - -1.2
    - 0.2
    - 1.2
    - 1.2
    - 2.0
    LID: false
    DEPTH_START: 0.2
    DEPTH_END: 2.0
    POINTS_FEAT_DIM: 256
    EMBED_DIMS: 256
    IN_CHANNELS: 128
    CENTER_SHIFT: true
    N_SAMPLE: 2048
    RADIUS_SAMPLE: 0.1
    OBJ_XYZ_UPDATE_SCALE: 0.05
    CAM_FEAT_MERGE: attn
    QUERY_TYPE: KPT
    STAGE2_HAND_UPDATE_MIN_SCALE: 0.2
    STAGE2_OBJ_FEAT_MIN_SCALE: 0.2
    STAGE2_POSE_DELTA_MIN_SCALE: 0.1
    STAGE2_INIT_ROT_MIN_SCALE: 0.1
  LOSS:
    JOINTS_LOSS_TYPE: l1
    VERTICES_LOSS_TYPE: l1
    HEATMAP_HAND_N: 1.0
    HEATMAP_OBJ_N: 1.0
    HEATMAP_HAND_MAP_N: 1.0
    HEATMAP_OBJ_MAP_N: 1.0
    OBJ_OCC_N: 1.0
    TRIANGULATION_N: 10.0
    TRIANGULATION_HAND_N: 10.0
    TRIANGULATION_OBJ_N: 1.0
    POSE_N: 0.01
    SHAPE_N: 1.0
    MANO_CONSIST_N: 10.0
    MANO_PROJ_N: 50.0
    DECODER_HAND_N: 10.0
    DECODER_PROJ_N: 10.0
    OBJ_POSE_ROT_N: 5.0
    OBJ_POSE_ROT6D_N: 0.1
    OBJ_INIT_ROT_N: 2.0
    OBJ_INIT_ROT6D_N: 0.1
    OBJ_VIEW_ROT_N: 1.0
    OBJ_VIEW_ROT6D_N: 0.05
    OBJ_POSE_TRANS_N: 10.0
    OBJ_POSE_POINTS_N: 10.0
    OBJ_CHAMFER_N: 2.0
    OBJ_EMD_N: 0.2
    OBJ_PENETRATION_N: 2.0
