TRAIN:
  MANUAL_SEED: 1
  CONV_REPEATABLE: true
  BATCH_SIZE: 8
  EPOCH: 200

  OPTIMIZER: adam
  LR: 0.00005
  WEIGHT_DECAY: 0.0
  SCHEDULER: StepLR
  LR_DECAY_STEP: [100]
  LR_DECAY_GAMMA: 1.0

  LOG_INTERVAL: 50
  FIND_UNUSED_PARAMETERS: false
  DEBUG_LOGS: false
  STATIC_GRAPH: false
  ALLOW_DIRTY_GIT: true

  STAGE1_END_EPOCH: 200
  STAGE2_WARMUP_EPOCHS: 0
  SV_SELF_DISTILL_ENABLED: false
  SV_SELF_DISTILL_START_EPOCH: 999999
  VAL_RECON_FULL_ONLY_FINAL: true

  GRAD_CLIP_ENABLED: true
  GRAD_CLIP:
    TYPE: 2
    NORM: 0.001

DATASET:
  TRAIN:
    TYPE: HO3Dv3MultiView
    DATA_MODE: 3D
    DATA_ROOT: /media/hl/nvme1TB/datasets
    DATA_SPLIT: train
    N_VIEWS: 5
    SPLIT_MODE: paper
    USE_GT_FROM_MULTIVIEW: true
    USE_LEFT_HAND: false
    MASTER_SYSTEM: as_constant_camera
    CONST_CAM_ID: 2
    TRANSFORM:
      TYPE: SimpleTransform3DMultiView
      AUG: true
      CENTER_JIT: 0.0
      SCALE_JIT: 0.06
      COLOR_JIT: 0.3
      ROT_JIT: 5
      ROT_PROB: 0.5
      OCCLUSION: true
      OCCLUSION_PROB: 0.2

  TEST:
    TYPE: HO3Dv3MultiView
    DATA_MODE: 3D
    DATA_ROOT: /media/hl/nvme1TB/datasets
    DATA_SPLIT: test
    N_VIEWS: 5
    SPLIT_MODE: paper
    USE_LEFT_HAND: false
    TEST_WITH_MULTIVIEW: true
    MASTER_SYSTEM: as_constant_camera
    CONST_CAM_ID: 2
    TRANSFORM:
      TYPE: SimpleTransform3DMultiView
      AUG: false

DATA_PRESET:
  MODE: mv
  USE_CACHE: true

  IMAGE_SIZE: [224, 224]
  CENTER_IDX: 0
  BBOX_3D_SIZE: 0.4
  NUM_JOINTS: 21
  NUM_VERTS: 778

  WITH_HEATMAP: false
  HEATMAP_SIZE: [28, 28]
  HEATMAP_SIGMA: 2.0
  WITH_MASK: false

  BBOX_EXPAND_RATIO: 1.2
  STAGE12_USE_HAND_OBJ_BBOX: true
  STAGE12_BBOX_EXPAND_RATIO: 1.2
  STAGE12_HAND_OBJ_SCALE: 1.2
  STAGE2_HAND_OBJ_SCALE: 1.2

MODEL:
  TYPE: POEM_SV_HOPRegNet
  PRETRAINED: null
  NUM_OBJ_JOINTS: 1
  HOPREG_HIDDEN_DIM: 512
  HOPREG_MANO:
    MANO_ASSETS_ROOT: assets/mano_v1_2
    INPUT_DIM: 512
    NCOMPS: 15
    USE_PCA: true
    USE_SHAPE: true
    SIDE: right

  BACKBONE:
    TYPE: ResNet34
    PRETRAINED: true
    FREEZE_BATCHNORM: false

  HEAD:
    TYPE: HOR_Projective_SelfAggregation_Head

    TRANSFORMER:
      TYPE: HORTR
      N_BLOCKS: 3
      INPUT_FEAT_DIM: 256
      NUM_HIDDEN_LAYERS: 4
      NUM_ATTENTION_HEADS: 4
      DROPOUT: 0.1
      N_NEIGHBOR: 32
      N_NEIGHBOR_QUERY: 32
      POINTS_FEAT_DIM: 256
      WITH_POSI_EMBED: true
      PREDICT_INV_SIGMOID: true
      PARAMETRIC_OUTPUT: true
      TRANSFORMER_CENTER_IDX: 0

    POSITIONAL_ENCODING:
      TYPE: SinePositionalEncoding3D
      NUM_FEATS: 128
      NORMALIZE: true

    WITH_POSITION: true
    WITH_MULTIVIEW: true
    NUM_QUERY: 799
    NUM_PREDS: 3
    DEPTH_NUM: 32
    POSITION_RANGE: [-0.6, -0.6, 0.0, 0.6, 0.6, 1.2]
    LID: false
    DEPTH_START: 0.0
    DEPTH_END: 1.2
    POINTS_FEAT_DIM: 256
    EMBED_DIMS: 256
    IN_CHANNELS: 128
    CENTER_SHIFT: true
    N_SAMPLE: 2048
    RADIUS_SAMPLE: 0.2
    OBJ_XYZ_UPDATE_SCALE: 0.05
    CAM_FEAT_MERGE: attn
    QUERY_TYPE: KPT
    STAGE2_HAND_UPDATE_MIN_SCALE: 0.2
    STAGE2_OBJ_FEAT_MIN_SCALE: 0.2
    STAGE2_POSE_DELTA_MIN_SCALE: 0.1
    STAGE2_INIT_ROT_MIN_SCALE: 0.1

  LOSS:
    JOINTS_LOSS_TYPE: l2
    VERTICES_LOSS_TYPE: l2

    HEATMAP_HAND_N: 0.0
    HEATMAP_OBJ_N: 0.0
    HEATMAP_HAND_MAP_N: 0.0
    HEATMAP_OBJ_MAP_N: 0.0

    TRIANGULATION_N: 0.0
    TRIANGULATION_HAND_N: 0.0
    TRIANGULATION_OBJ_N: 0.0

    POSE_N: 0.0
    SHAPE_N: 0.0
    MANO_CONSIST_N: 0.0
    MANO_PROJ_N: 0.0

    DECODER_HAND_N: 0.0
    DECODER_PROJ_N: 0.0

    OBJ_POSE_ROT_N: 0.0
    OBJ_POSE_ROT6D_N: 0.0
    OBJ_INIT_ROT_N: 0.0
    OBJ_INIT_ROT6D_N: 0.0
    OBJ_INIT_TRANS_N: 0.0
    OBJ_VIEW_ROT_N: 0.0
    OBJ_VIEW_ROT6D_N: 0.0
    OBJ_VIEW_TRANS_N: 0.0
    OBJ_POSE_TRANS_N: 0.0
    OBJ_POSE_POINTS_N: 0.0
    OBJ_CORNER_PROJ_N: 0.0
    OBJ_CORNER_3D_N: 0.0
    OBJ_CHAMFER_N: 0.0
    OBJ_EMD_N: 0.0
    OBJ_SYM_CORNER_N: 0.0
    OBJ_SYM_MAX_DISC_STEP: 0.01
    MODEL_INFO_PATH: /media/hl/nvme1TB/datasets/DexYCB/bop/models_eval/models_info.json
    OBJ_PENETRATION_N: 0.0

    ARTI_MANO_N: 1.0
    ARTI_JOINTS_GROUP_N: 1.0
    ARTI_MANO_JOINTS_3D_N: 0.0
    ARTI_MANO_VERTS_3D_N: 0.0
    ARTI_MANO_POSE_REG_N: 0.000005
    ARTI_MANO_SHAPE_REG_N: 0.0000005
    ARTI_CENTER_2D_N: 0.0
    ARTI_CENTER_3D_N: 0.0
    ARTI_JOINTS_3D_N: 1.0
    ARTI_VERTS_3D_N: 0.0
    ARTI_CORNERS_3D_N: 0.2
    ARTI_POINTS_3D_N: 0.0
    ARTI_SYM_CORNERS_3D_N: 0.0
    ARTI_HAND_ORD_N: 0.1
    ARTI_HAND_ORD_JOINT_N: 1.0
    ARTI_HAND_ORD_PART_N: 1.0
    ARTI_SCENE_ORD_N: 0.1
    ARTI_HAND_N_VIRTUAL_VIEWS: 20
    ARTI_SCENE_N_VIRTUAL_VIEWS: 40
